### ISSUE TITLE
无法同步下来

### ISSUE THREAD

**Issue by ManorNotMaNong** [mylhyl/Android-CircleDialog#1]
Error:(69, 13) Failed to resolve: com.mylhyl:circleDialog:2.0.0

**Comment by wsixsix** [comment]
我也是

**Comment by mylhyl** [comment]
compile 'com.mylhyl:circleDialog:2.1.6'

**Comment by wsixsix** [comment]
感谢，不好意识今天才看到～辛苦了～

2017-06-12 11:28 GMT+08:00 石头 <notifications@github.com>:
