### ISSUE TITLE
对话框背景颜色设置无效

### ISSUE THREAD

**Issue by AmioLee** [mylhyl/Android-CircleDialog#12]
.configDialog(new ConfigDialog() {
                                @Override
                                public void onConfig(DialogParams params) {
                                    params.backgroundColor = Color.BLACK;
                                }
                            })
                            .show();
设置di'alog背景无颜色无效

**Comment by mylhyl** [comment]
能否贴出全代码？我这边测试是有效果的

**Comment by AmioLee** [comment]
@mylhyl  
![tim 20180314115729](https://user-images.githubusercontent.com/32115721/37382684-0b1d84ea-277f-11e8-93d4-e71b4b5a52fe.png)

**Comment by mylhyl** [comment]
@AmioLee 你想要的效果是？这个背景参数基本没什么用，要改整体颜色只能通过，设置标题背景，内容背景，按钮背景来实现
