### ISSUE TITLE
能否开放设置输入框Gravity的接口？

### ISSUE THREAD

**Issue by ysutommy** [mylhyl/Android-CircleDialog#13]
目前输入框gravity默认是左上角  setGravity(Gravity.TOP | Gravity.LEFT)。且外部无法修改，希望能够公开这个接口，谢谢！

**Comment by mylhyl** [comment]
谢谢建议

**Comment by mylhyl** [comment]
compile 'com.mylhyl:circleDialog:2.4.1'

**Comment by ysutommy** [comment]
tks
