### ISSUE TITLE
请问 自定义List Adapter里面怎么实现单选

### ISSUE THREAD

**Issue by zjianflys** [mylhyl/Android-CircleDialog#17]

**Comment by mylhyl** [comment]
自己写好adapter
```java
	.setItems(checkedAdapter, new AdapterView.OnItemClickListener() {
		@Override
		public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
			checkedAdapter.toggle(position, objects[position]);
		}
	})
```

**Comment by zjianflys** [comment]
` @TargetApi(Build.VERSION_CODES.KITKAT)
    public void toggle(int key, java.lang.String value) {
        if (saveChecked.get(key) == null && saveChecked.size() < 1) {
            saveChecked.put(key, value);
        } else {
            saveChecked.removeAtRange(0, saveChecked.size());
            saveChecked.put(key, value);
        }
        notifyDataSetChanged();
    }`
这种写法有问题没得 ...

**Comment by zjianflys** [comment]
@TargetApi(Build.VERSION_CODES.KITKAT)
    public void toggle(int key, java.lang.String value) {
        if (saveChecked.get(key) == null && saveChecked.size() < 1) {
            saveChecked.put(key, value);
        } else {
            saveChecked.removeAtRange(0, saveChecked.size());
            saveChecked.put(key, value);
        }
        notifyDataSetChanged();
    }

> 这种写法有问题没得  楼主

**Comment by mylhyl** [comment]
能呈现你要的效果就行
最简单就是，Item每次点击时，把`saveChecked`给`clear`一次，再put进当前item
