### ISSUE TITLE
请问  多选或者单选 怎么设置下面多个按钮的  

### ISSUE THREAD

**Issue by zjianflys** [mylhyl/Android-CircleDialog#19]
我按属性设置没有用  显示不出来
 .setCancelable(false)
.setInputManualClose(true)

这两个设置了也没有用  是后面的冲突了嘛  
new CircleDialog.Builder()
                .configDialog(new ConfigDialog() {
                    @Override
                    public void onConfig(DialogParams params) {
                        params.backgroundColorPress = Color.GRAY;
                    }
                })
                .setTitle("选择特殊车辆类型[可不选择]")
                .setItems(singleAdapter, new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        singleAdapter.toggle(position, objects[position]);
                    }
                })
                .setGravity(Gravity.CENTER)//显示居中
                .setItemsManualClose(true)
                .setNegative("取消", null)
                .setPositive("下一步", new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                       
                    }
                })
                .show(getSupportFragmentManager());

**Comment by mylhyl** [comment]
列表模式目前只支持单个按钮，我会尽快满足你的需求！

**Comment by mylhyl** [comment]
compile 'com.mylhyl:circleDialog:2.5.5'
