### ISSUE TITLE
使用百分比布局导致不同分辨率的机子上效果有较大差异

### ISSUE THREAD

**Issue by protectedMan** [mylhyl/Android-CircleDialog#27]
这个是1080*1920屏幕的效果
![image](https://user-images.githubusercontent.com/17565737/43999352-6ce3ca42-9e3d-11e8-9173-4a3a5be2447b.png)

这个是1440*2880屏幕的效果
<img width="407" alt="image" src="https://user-images.githubusercontent.com/17565737/43999359-b21c4fbc-9e3d-11e8-8333-996115520cf7.png">

可以看出来，这两图取消(确认)按钮的高度与上部分内容的高度的比值是不相同的。

我的代码是这样设置的
<img width="827" alt="image" src="https://user-images.githubusercontent.com/17565737/43999390-1710c998-9e3e-11e8-9b45-caf32cc083fb.png">

**其实用dp适配下屏幕密度的就挺好的，一个对话框，还是不太适合用百分比布局。**

**Comment by mylhyl** [comment]
谢谢

**Comment by protectedMan** [comment]
v3版取消了百分比适配！ 太棒了
