### ISSUE TITLE
输入框对话框高度好像有问题，第一次显示只有一行，文字变更后显示正常高度

### ISSUE THREAD

**Issue by kzqsky** [mylhyl/Android-CircleDialog#37]
![tim 20190129165014](https://user-images.githubusercontent.com/2002252/51895791-fcf66580-23e5-11e9-967e-687959ef69ca.png)
![tim 20190129165024](https://user-images.githubusercontent.com/2002252/51895796-ff58bf80-23e5-11e9-98f1-51814e376c8d.png)

**Comment by mylhyl** [comment]
引用版本号是多少，也贴一下使用代码，谢谢！

**Comment by kzqsky** [comment]
> 引用版本号是多少，也贴一下使用代码，谢谢！

就是你的demo，3.0.5-alpha，Android 8.0系统
