### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ChenBu2** [mylhyl/Android-CircleDialog#38]
java.lang.NullPointerException:Attempt to invoke interface method 'android.view.View com.mylhyl.circledialog.view.listener.ItemsView.getView()' on a null object reference

出现了空指针异常，请问
@Override
    public ItemsView buildItems() {
        if (mItemsView == null) {
            if (mParams.itemListener != null || mParams.itemsParams.adapter != null)
                mItemsView = new BodyItemsView(mContext, mParams);
            else if (mParams.rvItemListener != null || mParams.itemsParams.adapterRv != null)
                mItemsView = new BodyItemsRvView(mContext, mParams);

            mRoot.addView(mItemsView.getView());
        }
        return mItemsView;
    }
这个怎么会为空呢，是因为设备部兼容么

**Comment by mylhyl** [comment]
麻烦贴一下使用的代码，谢谢！

**Comment by peiniwan** [comment]
遇到同样的问题

**Comment by mylhyl** [comment]
@peiniwan 麻烦贴一下使用的代码，谢谢！

**Comment by peiniwan** [comment]
![image](https://user-images.githubusercontent.com/13749946/53141873-c8cd2980-35cc-11e9-8928-5f2ddf962ef2.png)

**Comment by peiniwan** [comment]
![image](https://user-images.githubusercontent.com/13749946/53141955-147fd300-35cd-11e9-8a04-07f45b842a9a.png)

**Comment by mylhyl** [comment]
@peiniwan 引用的版本号是多少？android系统版本api等级是多少？谢谢

**Comment by peiniwan** [comment]
> @peiniwan 引用的版本号是多少？android系统版本api等级是多少？谢谢

2.6.6,Android 8.1.0,level 27

**Comment by mylhyl** [comment]
@peiniwan 2.6.7-beta 试试，谢谢！

**Comment by mylhyl** [comment]
@peiniwan 你好，测试没有重现你说的现象，能否告之你的应用场景和操作方式，弹出dialog就出错？还是选择了item的时候出错？
