### ISSUE TITLE
编辑对话框被键盘遮挡

### ISSUE THREAD

**Issue by folk113** [mylhyl/Android-CircleDialog#39]

**Comment by mylhyl** [comment]
请问用的是V3还是V2版本？android api等级是几？

**Comment by folk113** [comment]
implementation 'com.mylhyl:circleDialog:3.0.7'
华为荣耀android9

**Comment by mylhyl** [comment]
有调用setInputShowKeyboard(true)方法？要不把你的代码贴一下呗

**Comment by mylhyl** [comment]
3.0.7-beta
谢谢！
