### ISSUE TITLE
BodyRecyclerView dividerHeight设置无效

### ISSUE THREAD

**Issue by hx645021783** [mylhyl/Android-CircleDialog#40]
private void createItemDecoration() {
        if (mItemsParams.dividerHeight > 0 && !(mLayoutManager instanceof LayoutManager)) {
}
    }
这个取非应该是大佬手误吧？
!(mLayoutManager instanceof LayoutManager)

**Comment by mylhyl** [comment]
谢谢，已修复3.0.8
