### ISSUE TITLE
希望不要在构建的时候用getSupportFragmentManager

### ISSUE THREAD

**Issue by parkbaird** [mylhyl/Android-CircleDialog#44]
很多局限性

**Comment by mylhyl** [comment]
都是继承于`AppCompatActivity`开发，你有什么不同的应用场景？

**Comment by parkbaird** [comment]
Service


| |
王朴
邮箱：ltwangpu@163.com
|

签名由 网易邮箱大师 定制

在2019年05月15日 15:55，石头 写道：

都是继承于AppCompatActivity开发，你有什么不同的应用场景？

**Comment by mylhyl** [comment]
此库是基于dialogframent，只能依附于activity，抱歉！！！不过可以在service中启动一个activity来处理

**Comment by parkbaird** [comment]
好的


| |
王朴
邮箱：ltwangpu@163.com
|

签名由 网易邮箱大师 定制

在2019年05月15日 16:06，石头 写道：

此库是基于dialogframent，只能依附于activity，抱歉！！！不过可以在service中启动一个activity来处理
