### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View 

### ISSUE THREAD

**Issue by ChenBu2** [mylhyl/Android-CircleDialog#45]
Android 9.0 出现了这个异常，
06-11 12:18:41.674 11249 11249 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View com.mylhyl.circledialog.view.listener.ItemsView.getView()' on a null object reference
--
15506-11 12:18:41.674 11249 11249 E AndroidRuntime: at com.mylhyl.circledialog.view.BuildViewImpl.buildItems(BuildViewImpl.java:88)
15606-11 12:18:41.674 11249 11249 E AndroidRuntime: at com.mylhyl.circledialog.Controller.applyBody(Controller.java:82)
15706-11 12:18:41.674 11249 11249 E AndroidRuntime: at com.mylhyl.circledialog.Controller.createView(Controller.java:53)
15806-11 12:18:41.674 11249 11249 E AndroidRuntime: at com.mylhyl.circledialog.AbsCircleDialog.createView(AbsCircleDialog.java:50)
15906-11 12:18:41.674 11249 11249 E AndroidRuntime: at com.mylhyl.circledialog.BaseCircleDialog.onCreateView(BaseCircleDialog.java:70)
16006-11 12:18:41.674 11249 11249 E AndroidRuntime: at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
16106-11 12:18:41.674 11249 11249 E AndroidRuntime: at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
16206-11 12:18:41.674 11249 11249 E AndroidRuntime: at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
16306-11 12:18:41.674 11249 11249 E AndroidRuntime: at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
16406-11 12:18:41.674 11249 11249 E AndroidRuntime: at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
16506-11 12:18:41.674 11249 11249 E AndroidRuntime: at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
16606-11 12:18:41.674 11249 11249 E AndroidRuntime: at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)

**Comment by mylhyl** [comment]
哪个版本

**Comment by ChenBu2** [comment]
2.0.6

**Comment by mylhyl** [comment]
请升级至com.mylhyl:circleDialog:2.6.10

**Comment by ChenBu2** [comment]
好的，谢谢哈

**Comment by mylhyl** [comment]
不客气，如升级后再有问题，及时提出，谢谢支持

**Comment by ChenBu2** [comment]
好的

**Comment by ChenBu2** [comment]
你好，我看了下，最新版本你那边已经更新4.0.2了，需要更新到最新版本么

**Comment by mylhyl** [comment]
阅读https://github.com/mylhyl/Android-CircleDialog/wiki
有介绍各版本区别，依实际项目情况而升级！

**Comment by ChenBu2** [comment]
好的，谢谢
