### ISSUE TITLE
显示对话框后应用压入后台，由于内存不足等系统原因杀掉压入后台的应用时,对话框crash

### ISSUE THREAD

**Issue by wanghoubo** [mylhyl/Android-CircleDialog#49]
[log.txt](https://github.com/mylhyl/Android-CircleDialog/files/3549330/log.txt)；复现此现象的方法：设置--开发者选项--不保留活动（打开开关）；

**Comment by wanghoubo** [comment]
我测试的是3.0.10的版本

**Comment by wanghoubo** [comment]
当对话框显示时，点击HOME键压入后台后，由于内容不足或者其他原因导致应用被杀掉后，再次点击多任务栏中刚才被压入后台的应用，此时应用中显示对话框时会crash

**Comment by mylhyl** [comment]
如果是最新版本，请贴出崩溃日志，谢谢！

**Comment by mylhyl** [comment]
收到，谢谢

**Comment by mylhyl** [comment]
https://github.com/mylhyl/Android-CircleDialog/tree/v3
