### ISSUE TITLE
关于CircleDialog 的show(getSupportFragmentManager())方法建议

### ISSUE THREAD

**Issue by jinhuizxc** [mylhyl/Android-CircleDialog#50]
show(getSupportFragmentManager())最后显示的部分似乎都是这个写法，这就造成了circleDialog的显示必须依赖于activity或者是fragment，能不能后期将dialog做成不依赖与界面，在其他类里面也可以自由调用呢？

**Comment by mylhyl** [comment]
@jinhuizxc 
https://github.com/mylhyl/Android-CircleDialog/issues/44#issuecomment-492551562
