### ISSUE TITLE
关于序列化的一些疑问

### ISSUE THREAD

**Issue by HeMing123** [mylhyl/Android-CircleDialog#53]
BaseCircleDialog类中通过序列化保存一些参数信息,但是CircleParams中的点击事件并不会被序列化,so当FragmentDialog重建时,点击事件是否会丢失?
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putParcelable(SAVED_PARAMS, mParams);
    }

**Comment by mylhyl** [comment]
被你发现了，暂时没有想到好方式，有没有啥思路？

**Comment by HeMing123** [comment]
https://github.com/tianzhijiexian/EasyDialog

**Comment by mylhyl** [comment]
> 
> 
> https://github.com/tianzhijiexian/EasyDialog

谢谢，但是该库是activity必须实现点击事件接口哦，这还是硬编码了。
