### ISSUE TITLE
AbsBaseCircleDialog 继承这个 自定义dialog

### ISSUE THREAD

**Issue by zjianflys** [mylhyl/Android-CircleDialog#54]
对androidx.recyclerview.widget.RecyclerView 没有兼容一直报Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.RecyclerView"

布局文件为：
`<?xml version="1.0" encoding="utf-8"?>
<com.zhy.autolayout.AutoLinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#333333">

        <ImageView
            android:id="@+id/iv_close"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_marginTop="5dp"
            android:layout_marginRight="10dp"
            android:layout_marginBottom="5dp"
            android:src="@drawable/selector_btn_province1_bg" />
    </RelativeLayout>

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/revList"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#c9c9c9"
        android:paddingLeft="@dimen/dimen10"
        android:paddingTop="@dimen/dimen8"
        android:paddingRight="@dimen/dimen5"
        android:paddingBottom="@dimen/dimen5" />

</com.zhy.autolayout.AutoLinearLayout>

`

**Comment by zjianflys** [comment]
`    @Override
    public View createView(Context context, LayoutInflater inflater, ViewGroup container) {
        return inflater.inflate(R.layout.view_dialog_province, container, false);
    }`
主要在这行报错

**Comment by mylhyl** [comment]
版本号是多少？




| |
hupei132
|
|
邮箱：hupei132@163.com
|

Signature is customized by Netease Mail Master

在2020年01月16日 15:31，飞飞 写道：

@Override public View createView(Context context, LayoutInflater inflater, ViewGroup container) { return inflater.inflate(R.layout.view_dialog_province, container, false); }
主要在这行报错

**Comment by zjianflys** [comment]
"circleDialog"                 : "com.mylhyl:circleDialog:5.0.7",

**Comment by mylhyl** [comment]
收到

**Comment by mylhyl** [comment]
> 
> 
> "circleDialog" : "com.mylhyl:circleDialog:5.0.7",

你好，能给出具体的日志吗？或者加一下我微信号h-98t1
