### ISSUE TITLE
我的Bugly检测到这个问题

### ISSUE THREAD

**Issue by aichixiguaj** [mylhyl/Android-CircleDialog#55]
#3604 java.lang.NullPointerException
Attempt to read from field 'com.mylhyl.circledialog.params.PopupParams com.mylhyl.circledialog.CircleParams.popupParams' on a null object reference

com.mylhyl.circledialog.BaseCircleDialog.onShow(BaseCircleDialog.java:128)

**Comment by mylhyl** [comment]
哪个版本？




| |
hupei132
|
|
邮箱：hupei132@163.com
|

Signature is customized by Netease Mail Master

在2020年01月18日 17:02，SomebodyNameMe 写道：

#3604 java.lang.NullPointerException
Attempt to read from field 'com.mylhyl.circledialog.params.PopupParams com.mylhyl.circledialog.CircleParams.popupParams' on a null object reference

com.mylhyl.circledialog.BaseCircleDialog.onShow(BaseCircleDialog.java:128)

**Comment by SomebodyNameMe** [comment]
5.0.4

**Comment by aichixiguaj** [comment]
> 哪个版本？ | | hupei132 | | 邮箱：hupei132@163.com | Signature is customized by Netease Mail Master 在2020年01月18日 17:02，SomebodyNameMe 写道： #3604 java.lang.NullPointerException Attempt to read from field 'com.mylhyl.circledialog.params.PopupParams com.mylhyl.circledialog.CircleParams.popupParams' on a null object reference com.mylhyl.circledialog.BaseCircleDialog.onShow(BaseCircleDialog.java:128) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

版本：5.0.4

**Comment by mylhyl** [comment]
收到

**Comment by mylhyl** [comment]
> 
> 
> > 哪个版本？ | | hupei132 | | 邮箱：[hupei132@163.com](mailto:hupei132@163.com) | Signature is customized by Netease Mail Master 在2020年01月18日 17:02，SomebodyNameMe 写道： #3604 java.lang.NullPointerException Attempt to read from field 'com.mylhyl.circledialog.params.PopupParams com.mylhyl.circledialog.CircleParams.popupParams' on a null object reference com.mylhyl.circledialog.BaseCircleDialog.onShow(BaseCircleDialog.java:128) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 版本：5.0.4

5.0.7已经修复
