### ISSUE TITLE
列表对话框无法居中显示

### ISSUE THREAD

**Issue by qinhuangran** [mylhyl/Android-CircleDialog#56]
ConfigDialog configDialog = new ConfigDialog() {
            @Override
            public void onConfig(DialogParams params) {
                params.gravity = Gravity.CENTER;
                int ih = getResources().getDimensionPixelOffset(R.dimen.dialog_item_height);
                int th = getResources().getDimensionPixelOffset(R.dimen.dialog_title_height);
                params.maxHeight = ih * strs.length + th;
            }
        };
  CircleDialog.Builder builder = new CircleDialog.Builder()
                .setTitle("Adjust brightness")//内容
                .setTitleColor(getResources().getColor(R.color.black))
                .configTitle(configTitle)
                .setItems(Arrays.asList(strs), new OnRvItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position) {
                        return false;
                    }
                }).configItems(configItems).configDialog(configDialog).setGravity(Gravity.CENTER);
builder对象setGravity(Gravity.CENTER)也不起作用，已尝试各中办法还是无法设置居中显示。

**Comment by mylhyl** [comment]
@huangran-qin 哪个版本？

**Comment by qinhuangran** [comment]
@mylhyl com.mylhyl:circleDialog:3.0.11

**Comment by qinhuangran** [comment]
版本问题，换了3.1.0，OK,不好意思，打扰了。

**Comment by mylhyl** [comment]
> 
> 
> 版本问题，换了3.1.0，OK,不好意思，打扰了。

不是版本问题，是bug，今天更新的，感谢反馈
