### ISSUE TITLE
希望增加按键监听接口

### ISSUE THREAD

**Issue by Linpeita** [mylhyl/Android-CircleDialog#57]
类似这个按键监听，可以监听HOME键、MENU键、BACK键
this.getDialog().setOnKeyListener(new OnKeyListener()
        {
           public boolean onKey(DialogInterface dialog, int keyCode, KeyEvent event){
           
         }
       });

**Comment by mylhyl** [comment]
@Linpeita ok

**Comment by Linpeita** [comment]
更新完成通知下噢，谢谢了~  O(∩_∩)O
