### ISSUE TITLE
How to apply font

### ISSUE THREAD

**Issue by HamedTaherpour** [mylhyl/Android-CircleDialog#58]
Can I apply my favorite font to it?

Thank you

**Comment by mylhyl** [comment]
please see [TitleParams#styleText](https://github.com/mylhyl/Android-CircleDialog/blob/master/circledialog/src/main/java/com/mylhyl/circledialog/params/TitleParams.java)
[other parameters are similar](https://github.com/mylhyl/Android-CircleDialog/tree/master/circledialog/src/main/java/com/mylhyl/circledialog/params)

**Comment by HamedTaherpour** [comment]
Thanks, but ''styleText'' doesn't change the font for me 
[See
](https://github.com/mylhyl/Android-CircleDialog/search?q=setTypeface&unscoped_q=setTypeface)I want to set the "Typeface"
For example, this

```
Typeface type = Typeface.createFromAsset(getAssets(),"fonts/arial.ttf"); 
textView.setTypeface(type);
```

**Comment by mylhyl** [comment]
ok, i get it

**Comment by HamedTaherpour** [comment]
Thank you so much
