### ISSUE TITLE
希望CircleDialog.Builder增加dismiss的方法

### ISSUE THREAD

**Issue by Linpeita** [mylhyl/Android-CircleDialog#60]
十分感谢！

**Comment by mylhyl** [comment]
哪个版本？

**Comment by mylhyl** [comment]
能说说使用场景吗？

**Comment by Linpeita** [comment]
> 能说说使用场景吗？

场景是这样的：弹窗后，在某个条件达成时，我需要代码手动关闭弹窗。

**Comment by mylhyl** [comment]
5.3.0

**Comment by Linpeita** [comment]
> 5.3.0

好的，我测试一下。非常感谢！

**Comment by Linpeita** [comment]
> > 5.3.0
> 
> 好的，我测试一下。非常感谢！

我测试了下，已经有dismiss接口了，但是我调用后，关闭弹窗后会马上又弹窗出来，看起来并没有关闭。

**Comment by mylhyl** [comment]
请贴代码，提供的信息太少了，我需要明白你的具体需求和使用




| |
hupei132
|
|
邮箱：hupei132@163.com
|

Signature is customized by Netease Mail Master

在2020年05月20日 09:55，Linpeita 写道：

5.3.0

好的，我测试一下。非常感谢！

我测试了下，已经有dismiss接口了，但是我调用后，关闭弹窗后会马上又弹窗出来，看起来并没有关闭。

**Comment by Linpeita** [comment]
> > > 5.3.0
> > 
> > 
> > 好的，我测试一下。非常感谢！
> 
> 我测试了下，已经有dismiss接口了，但是我调用后，关闭弹窗后会马上又弹窗出来，看起来并没有关闭。

不好意思，我调用有问题。因为调用show接口两次，导致实际有2个弹窗，只dismiss一次，所以效果上来看还存在一个弹窗。
目前已经可以了，再次感谢。
