### ISSUE TITLE
自定义对话框的body报错

### ISSUE THREAD

**Issue by passerbyYSQ** [mylhyl/Android-CircleDialog#61]
new CircleDialog.Builder()
                        .setTitle("加群")
                        .setBodyView(R.layout.dialog_join_group, null)
                        .setInputShowKeyboard(true)//自动弹出键盘
                        .setCancelable(false)
                        .setPositiveInput("确定", new OnInputClickListener() {
                            @Override
                            public boolean onClick(String text, View v) {
                                UiHelper.showToast("确定");
                                EditText mEnterPassword = v.findViewById(R.id.txt_enter_password);
                                EditText mAlias = v.findViewById(R.id.txt_my_alias);

                                String enterPassword = mEnterPassword.getText().toString().trim();
                                String alias = mAlias.getText().toString().trim();

                                if (TextUtils.isEmpty(enterPassword)) {
                                    UiHelper.showToast("加群密码不能为空");
                                    return false;
                                } else if (TextUtils.isEmpty(alias)) {
                                    UiHelper.showToast("备注名不能为空");
                                    return false;
                                } else {
                                    requestJoinGroup(new JoinGroupModel(
                                            mData.getGroupId(), enterPassword, alias), mData);
                                    return true;
                                }
                            }
                        })
                        .setNegative("取消", null)
                        .show(getChildFragmentManager());

布局文件：
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:paddingStart="@dimen/len_16"
    android:paddingEnd="@dimen/len_16">

    <EditText
        android:id="@+id/txt_enter_password"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:inputType="textPassword"
        android:hint="加群密码" />

    <EditText
        android:id="@+id/txt_my_alias"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="您在群内的备注名" />

</LinearLayout>

我是个Android初学者，我想自定义Dialog里面body的布局。但是运行点击后崩溃报错。
不知道是不是我调用有问题？

**Comment by mylhyl** [comment]
自定义body的场景，那按钮事件与body之间就没有关联了




| |
hupei132
|
|
邮箱：hupei132@163.com
|

Signature is customized by Netease Mail Master

在2020年05月16日 21:18，passerbyYSQ 写道：

new CircleDialog.Builder()
.setTitle("加群")
.setBodyView(R.layout.dialog_join_group, null)
.setInputShowKeyboard(true)//自动弹出键盘
.setCancelable(false)
.setPositiveInput("确定", new OnInputClickListener() {
@override
public boolean onClick(String text, View v) {
UiHelper.showToast("确定");
EditText mEnterPassword = v.findViewById(R.id.txt_enter_password);
EditText mAlias = v.findViewById(R.id.txt_my_alias);

                            String enterPassword = mEnterPassword.getText().toString().trim();

                            String alias = mAlias.getText().toString().trim();



                            if (TextUtils.isEmpty(enterPassword)) {

                                UiHelper.showToast("加群密码不能为空");

                                return false;

                            } else if (TextUtils.isEmpty(alias)) {

                                UiHelper.showToast("备注名不能为空");

                                return false;

                            } else {

                                requestJoinGroup(new JoinGroupModel(

                                        mData.getGroupId(), enterPassword, alias), mData);

                                return true;

                            }

                        }

                    })

                    .setNegative("取消", null)

                    .show(getChildFragmentManager());



布局文件：

<EditText

    android:id="@+id/txt_enter_password"

    android:layout_width="match_parent"

    android:layout_height="wrap_content"

    android:inputType="textPassword"

    android:hint="加群密码" />



<EditText

    android:id="@+id/txt_my_alias"

    android:layout_width="match_parent"

    android:layout_height="wrap_content"

    android:hint="您在群内的备注名" />



我是个Android初学者，我想自定义Dialog里面body的布局。但是运行点击后崩溃报错。
不知道是不是我调用有问题？

**Comment by passerbyYSQ** [comment]
大佬，我现在有个需求，我想在dialog的body里面定义两个EditText。用您的框架，有没有办法做到这个？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"八阿哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 晚上9:22
收件人:&nbsp;"mylhyl/Android-CircleDialog"<Android-CircleDialog@noreply.github.com&gt;;
抄送:&nbsp;"过路人"<1127664027@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mylhyl/Android-CircleDialog] 自定义对话框的body报错 (#61)





 自定义body的场景，那按钮事件与body之间就没有关联了
 
 
 
 
 | |
 hupei132
 |
 |
 邮箱：hupei132@163.com
 |
 
 Signature is customized by Netease Mail Master
 
 在2020年05月16日 21:18，passerbyYSQ 写道：
 
 new CircleDialog.Builder()
 .setTitle("加群")
 .setBodyView(R.layout.dialog_join_group, null)
 .setInputShowKeyboard(true)//自动弹出键盘
 .setCancelable(false)
 .setPositiveInput("确定", new OnInputClickListener() {
 @override
 public boolean onClick(String text, View v) {
 UiHelper.showToast("确定");
 EditText mEnterPassword = v.findViewById(R.id.txt_enter_password);
 EditText mAlias = v.findViewById(R.id.txt_my_alias);
 
                             String enterPassword = mEnterPassword.getText().toString().trim();
 
                             String alias = mAlias.getText().toString().trim();
 
 
 
                             if (TextUtils.isEmpty(enterPassword)) {
 
                                 UiHelper.showToast("加群密码不能为空");
 
                                 return false;
 
                             } else if (TextUtils.isEmpty(alias)) {
 
                                 UiHelper.showToast("备注名不能为空");
 
                                 return false;
 
                             } else {
 
                                 requestJoinGroup(new JoinGroupModel(
 
                                         mData.getGroupId(), enterPassword, alias), mData);
 
                                 return true;
 
                             }
 
                         }
 
                     })
 
                     .setNegative("取消", null)
 
                     .show(getChildFragmentManager());
 
 
 
 布局文件：
 
 <EditText
 
     android:id="@+id/txt_enter_password"
 
     android:layout_width="match_parent"
 
     android:layout_height="wrap_content"
 
     android:inputType="textPassword"
 
     android:hint="加群密码" /&gt;
 
 
 
 <EditText
 
     android:id="@+id/txt_my_alias"
 
     android:layout_width="match_parent"
 
     android:layout_height="wrap_content"
 
     android:hint="您在群内的备注名" /&gt;
 
 
 
 我是个Android初学者，我想自定义Dialog里面body的布局。但是运行点击后崩溃报错。
 不知道是不是我调用有问题？

**Comment by mylhyl** [comment]
可以的




| |
hupei132
|
|
邮箱：hupei132@163.com
|

Signature is customized by Netease Mail Master

在2020年05月16日 21:26，passerbyYSQ 写道：

大佬，我现在有个需求，我想在dialog的body里面定义两个EditText。用您的框架，有没有办法做到这个？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"八阿哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 晚上9:22
收件人:&nbsp;"mylhyl/Android-CircleDialog"<Android-CircleDialog@noreply.github.com&gt;;
抄送:&nbsp;"过路人"<1127664027@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mylhyl/Android-CircleDialog] 自定义对话框的body报错 (#61)





自定义body的场景，那按钮事件与body之间就没有关联了




| |
hupei132
|
|
邮箱：hupei132@163.com
|

Signature is customized by Netease Mail Master

在2020年05月16日 21:18，passerbyYSQ 写道：

new CircleDialog.Builder()
.setTitle("加群")
.setBodyView(R.layout.dialog_join_group, null)
.setInputShowKeyboard(true)//自动弹出键盘
.setCancelable(false)
.setPositiveInput("确定", new OnInputClickListener() {
@override
public boolean onClick(String text, View v) {
UiHelper.showToast("确定");
EditText mEnterPassword = v.findViewById(R.id.txt_enter_password);
EditText mAlias = v.findViewById(R.id.txt_my_alias);

String enterPassword = mEnterPassword.getText().toString().trim();

String alias = mAlias.getText().toString().trim();



if (TextUtils.isEmpty(enterPassword)) {

UiHelper.showToast("加群密码不能为空");

return false;

} else if (TextUtils.isEmpty(alias)) {

UiHelper.showToast("备注名不能为空");

return false;

} else {

requestJoinGroup(new JoinGroupModel(

mData.getGroupId(), enterPassword, alias), mData);

return true;

}

}

})

.setNegative("取消", null)

.show(getChildFragmentManager());



布局文件：

<EditText

android:id="@+id/txt_enter_password"

android:layout_width="match_parent"

android:layout_height="wrap_content"

android:inputType="textPassword"

android:hint="加群密码" /&gt;



<EditText

android:id="@+id/txt_my_alias"

android:layout_width="match_parent"

android:layout_height="wrap_content"

android:hint="您在群内的备注名" /&gt;



我是个Android初学者，我想自定义Dialog里面body的布局。但是运行点击后崩溃报错。
不知道是不是我调用有问题？

**Comment by passerbyYSQ** [comment]
大佬，您多说一点。。我在上Android课程，是个初学者。您多说一点，多指导一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"八阿哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 晚上9:35
收件人:&nbsp;"mylhyl/Android-CircleDialog"<Android-CircleDialog@noreply.github.com&gt;;
抄送:&nbsp;"过路人"<1127664027@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mylhyl/Android-CircleDialog] 自定义对话框的body报错 (#61)





 可以的
 
 
 
 
 | |
 hupei132
 |
 |
 邮箱：hupei132@163.com
 |
 
 Signature is customized by Netease Mail Master
 
 在2020年05月16日 21:26，passerbyYSQ 写道：
 
 大佬，我现在有个需求，我想在dialog的body里面定义两个EditText。用您的框架，有没有办法做到这个？
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"八阿哥"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年5月16日(星期六) 晚上9:22
 收件人:&amp;nbsp;"mylhyl/Android-CircleDialog"<Android-CircleDialog@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"过路人"<1127664027@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [mylhyl/Android-CircleDialog] 自定义对话框的body报错 (#61)
 
 
 
 
 
 自定义body的场景，那按钮事件与body之间就没有关联了
 
 
 
 
 | |
 hupei132
 |
 |
 邮箱：hupei132@163.com
 |
 
 Signature is customized by Netease Mail Master
 
 在2020年05月16日 21:18，passerbyYSQ 写道：
 
 new CircleDialog.Builder()
 .setTitle("加群")
 .setBodyView(R.layout.dialog_join_group, null)
 .setInputShowKeyboard(true)//自动弹出键盘
 .setCancelable(false)
 .setPositiveInput("确定", new OnInputClickListener() {
 @override
 public boolean onClick(String text, View v) {
 UiHelper.showToast("确定");
 EditText mEnterPassword = v.findViewById(R.id.txt_enter_password);
 EditText mAlias = v.findViewById(R.id.txt_my_alias);
 
 String enterPassword = mEnterPassword.getText().toString().trim();
 
 String alias = mAlias.getText().toString().trim();
 
 
 
 if (TextUtils.isEmpty(enterPassword)) {
 
 UiHelper.showToast("加群密码不能为空");
 
 return false;
 
 } else if (TextUtils.isEmpty(alias)) {
 
 UiHelper.showToast("备注名不能为空");
 
 return false;
 
 } else {
 
 requestJoinGroup(new JoinGroupModel(
 
 mData.getGroupId(), enterPassword, alias), mData);
 
 return true;
 
 }
 
 }
 
 })
 
 .setNegative("取消", null)
 
 .show(getChildFragmentManager());
 
 
 
 布局文件：
 
 <EditText
 
 android:id="@+id/txt_enter_password"
 
 android:layout_width="match_parent"
 
 android:layout_height="wrap_content"
 
 android:inputType="textPassword"
 
 android:hint="加群密码" /&amp;gt;
 
 
 
 <EditText
 
 android:id="@+id/txt_my_alias"
 
 android:layout_width="match_parent"
 
 android:layout_height="wrap_content"
 
 android:hint="您在群内的备注名" /&amp;gt;
 
 
 
 我是个Android初学者，我想自定义Dialog里面body的布局。但是运行点击后崩溃报错。
 不知道是不是我调用有问题？

**Comment by mylhyl** [comment]
代码就是最好的老师，可以阅读demo或者在readme找我联系方式




| |
hupei132
|
|
邮箱：hupei132@163.com
|

Signature is customized by Netease Mail Master

在2020年05月16日 21:39，passerbyYSQ 写道：

大佬，您多说一点。。我在上Android课程，是个初学者。您多说一点，多指导一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"八阿哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 晚上9:35
收件人:&nbsp;"mylhyl/Android-CircleDialog"<Android-CircleDialog@noreply.github.com&gt;;
抄送:&nbsp;"过路人"<1127664027@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mylhyl/Android-CircleDialog] 自定义对话框的body报错 (#61)





可以的




| |
hupei132
|
|
邮箱：hupei132@163.com
|

Signature is customized by Netease Mail Master

在2020年05月16日 21:26，passerbyYSQ 写道：

大佬，我现在有个需求，我想在dialog的body里面定义两个EditText。用您的框架，有没有办法做到这个？




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"八阿哥"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2020年5月16日(星期六) 晚上9:22
收件人:&amp;nbsp;"mylhyl/Android-CircleDialog"<Android-CircleDialog@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"过路人"<1127664027@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [mylhyl/Android-CircleDialog] 自定义对话框的body报错 (#61)





自定义body的场景，那按钮事件与body之间就没有关联了




| |
hupei132
|
|
邮箱：hupei132@163.com
|

Signature is customized by Netease Mail Master

在2020年05月16日 21:18，passerbyYSQ 写道：

new CircleDialog.Builder()
.setTitle("加群")
.setBodyView(R.layout.dialog_join_group, null)
.setInputShowKeyboard(true)//自动弹出键盘
.setCancelable(false)
.setPositiveInput("确定", new OnInputClickListener() {
@override
public boolean onClick(String text, View v) {
UiHelper.showToast("确定");
EditText mEnterPassword = v.findViewById(R.id.txt_enter_password);
EditText mAlias = v.findViewById(R.id.txt_my_alias);

String enterPassword = mEnterPassword.getText().toString().trim();

String alias = mAlias.getText().toString().trim();



if (TextUtils.isEmpty(enterPassword)) {

UiHelper.showToast("加群密码不能为空");

return false;

} else if (TextUtils.isEmpty(alias)) {

UiHelper.showToast("备注名不能为空");

return false;

} else {

requestJoinGroup(new JoinGroupModel(

mData.getGroupId(), enterPassword, alias), mData);

return true;

}

}

})

.setNegative("取消", null)

.show(getChildFragmentManager());



布局文件：

<EditText

android:id="@+id/txt_enter_password"

android:layout_width="match_parent"

android:layout_height="wrap_content"

android:inputType="textPassword"

android:hint="加群密码" /&amp;gt;



<EditText

android:id="@+id/txt_my_alias"

android:layout_width="match_parent"

android:layout_height="wrap_content"

android:hint="您在群内的备注名" /&amp;gt;



我是个Android初学者，我想自定义Dialog里面body的布局。但是运行点击后崩溃报错。
不知道是不是我调用有问题？
