### ISSUE TITLE
能否在下面三个按钮增加焦点的属性？

### ISSUE THREAD

**Issue by zjianflys** [mylhyl/Android-CircleDialog#67]
我现在应用在电视当中, android:focusable="true"   android:focusableInTouchMode="true" 这两个属性不设置,遥控器获取不到焦点

**Comment by mylhyl** [comment]
[wiki](https://github.com/mylhyl/Android-CircleDialog/wiki/%E6%99%AE%E9%80%9A%E5%AF%B9%E8%AF%9D%E6%A1%86)有教程
如果api不够用，可以调用[setOnCreateButtonListener](https://github.com/mylhyl/Android-CircleDialog/blob/master/circledialog/src/main/java/com/mylhyl/circledialog/view/listener/OnCreateButtonListener.java)监听器
