### ISSUE TITLE
继承 AbsBaseCircleDialog 的时候背景是透明的

### ISSUE THREAD

**Issue by zjianflys** [mylhyl/Android-CircleDialog#68]
我发现在xml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@drawable/shape_corners_bg"
        android:orientation="vertical">

        <TextView
            android:id="@+id/tv_title"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="60dp"
            android:layout_marginTop="30dp"
            android:layout_marginRight="60dp"
            android:gravity="center"
            android:text="欢迎使用，请登录!"
            android:textColor="#3f454d"
            android:textSize="25sp" />

        <EditText
            android:id="@+id/et_user"
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:layout_marginLeft="60dp"
            android:layout_marginTop="40dp"
            android:layout_marginRight="60dp"
            android:background="@drawable/shape_input_normal"
            android:hint="请输入用户名"
            android:paddingLeft="15dp" />

        <EditText
            android:id="@+id/et_pass"
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:layout_marginLeft="60dp"
            android:layout_marginTop="40dp"
            android:layout_marginRight="60dp"
            android:background="@drawable/shape_input_normal"
            android:hint="请输入密码"
            android:paddingLeft="15dp" />

        <Button
            android:id="@+id/btn_login"
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:layout_marginLeft="60dp"
            android:layout_marginTop="40dp"
            android:layout_marginRight="60dp"
            android:layout_marginBottom="30dp"
            android:background="@drawable/selector_btn_corners"
            android:text="登&#160;&#160;录"
            android:textColor="@color/white"
            android:textSize="17sp" />
    </LinearLayout>
</LinearLayout>
`
这里需要在外面包2层才能实现圆角效果

**Comment by mylhyl** [comment]
![图片](https://user-images.githubusercontent.com/5705236/88054839-97c1a180-cb90-11ea-9823-dd547fcb77ed.png)
`AbsBaseCircleDialog`#`onViewCreated`函数中已经内置了圆角

**Comment by luncang** [comment]
> 我发现在xml
> `
> ```
> <LinearLayout
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     android:background="@drawable/shape_corners_bg"
>     android:orientation="vertical">
> 
>     <TextView
>         android:id="@+id/tv_title"
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:layout_marginLeft="60dp"
>         android:layout_marginTop="30dp"
>         android:layout_marginRight="60dp"
>         android:gravity="center"
>         android:text="欢迎使用，请登录!"
>         android:textColor="#3f454d"
>         android:textSize="25sp" />
> 
>     <EditText
>         android:id="@+id/et_user"
>         android:layout_width="match_parent"
>         android:layout_height="50dp"
>         android:layout_marginLeft="60dp"
>         android:layout_marginTop="40dp"
>         android:layout_marginRight="60dp"
>         android:background="@drawable/shape_input_normal"
>         android:hint="请输入用户名"
>         android:paddingLeft="15dp" />
> 
>     <EditText
>         android:id="@+id/et_pass"
>         android:layout_width="match_parent"
>         android:layout_height="50dp"
>         android:layout_marginLeft="60dp"
>         android:layout_marginTop="40dp"
>         android:layout_marginRight="60dp"
>         android:background="@drawable/shape_input_normal"
>         android:hint="请输入密码"
>         android:paddingLeft="15dp" />
> 
>     <Button
>         android:id="@+id/btn_login"
>         android:layout_width="match_parent"
>         android:layout_height="50dp"
>         android:layout_marginLeft="60dp"
>         android:layout_marginTop="40dp"
>         android:layout_marginRight="60dp"
>         android:layout_marginBottom="30dp"
>         android:background="@drawable/selector_btn_corners"
>         android:text="登&#160;&#160;录"
>         android:textColor="@color/white"
>         android:textSize="17sp" />
> </LinearLayout>
> ```
> 
> ` 这里需要在外面包2层才能实现圆角效果

我也发现了，哈哈哈，确实需要弄两层，他这个代码是有问题的
